### ISSUE TITLE
TypeError: plugin.merge_redis_ini is not a function when loading plugin config

### ISSUE THREAD

**Issue by The-Nutty** [haraka/Haraka#2726]
### system info

Built using the following docker file, run on amazon linux:
```
FROM node:12
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --only=production
RUN npm install -g Haraka --unsafe
COPY . .
EXPOSE 25
CMD [ "npm", "start" ]
```

### Expected behavior
Haraka should load config files and start correctly after upgrading from V2.8.23 -> V2.8.25
### Observed behavior
haraka crashes with the following logs:
```
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] TypeError: plugin.merge_redis_ini is not a function
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Plugin.exports.load_limit_ini (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-limit/index.js:84:12)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Plugin.exports.register (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-limit/index.js:13:12)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Object.plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:376:12)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:350:17)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at /usr/local/lib/node_modules/Haraka/plugins.js:322:17
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Array.forEach (<anonymous>)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Object.plugins.load_plugins (/usr/local/lib/node_modules/Haraka/plugins.js:321:17)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:295:20)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
2019-10-23 13:23:352019-10-23T12:23:35.277Z [CRIT] [-] [core] at Module._compile (internal/modules/cjs/loader.js:956:30)


```

### Steps to reproduce
I have a minimal haraka config with just the tls, max_unrecognized_commands (same issue occurs using limit) and a few custom pugins.

**Comment by msimerson** [comment]
The limit plugin requires the redis plugin to be loaded as well. Add it to your `config/plugins` file and that should resolve your issue.
